database_config:
  database_type: both  # Вказуємо 'both', якщо хочемо підключити обидві бази даних

  sqlite_database:
    db_file: local_database.sqlite
    timeout: 5000
    pool_size: 5

  mongodb_database:
    uri: "mongodb://localhost:27017/?connectTimeoutMS=20000"  # Збільшіть до 20 секунд
    db_name: my_database


