default:
  # Вказує на кореневу директорію проєкту
  root_dir: <%= File.expand_path('../', __FILE__) %>
  
  # Директорія, де зберігаються конфігураційні файли
  config_dir: config
  
  # Директорія для YAML конфігурацій
  yaml_dir: config/yaml_config
  
  # Директорія для медіа-файлів (зображення, відео тощо)
  media_dir: media
